server:
  port: ${APP_PORT:8002}

openapi:
  server:
    url: ${OPENAPI_SERVER_URL:http://localhost:8080}

spring:
  application:
    name: recipe-service
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:10MB}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/recipe_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: ${JPA_SHOW_SQL:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  seed-data:
    enabled: ${APP_SEED_DATA_ENABLED:true}
  cloudinary:
    enabled: ${APP_CLOUDINARY_ENABLED:true}
    cloud-name: ${CLOUDINARY_CLOUD_NAME:mss301}
    api-key: ${CLOUDINARY_API_KEY:429768692751461}
    api-secret: ${CLOUDINARY_API_SECRET:p9AhIOkrKBk4CRECSKDBFsPpdz4}
    folder: ${CLOUDINARY_FOLDER:mss301/recipes}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
