CREATE TYPE meal_type_enum AS ENUM ('breakfast', 'lunch', 'dinner', 'snack');

CREATE TABLE ai_suggestion (
    suggestion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE suggested_recipe (
    suggested_recipe_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    score DECIMAL(10, 2) NOT NULL,
    reason TEXT,
    rank INT NOT NULL,
    CONSTRAINT fk_suggested_recipe_suggestion
        FOREIGN KEY (suggestion_id) REFERENCES ai_suggestion (suggestion_id) ON DELETE CASCADE,
    CONSTRAINT ck_suggested_recipe_score CHECK (score >= 0),
    CONSTRAINT ck_suggested_recipe_rank CHECK (rank > 0),
    CONSTRAINT uk_suggested_recipe_suggestion_rank UNIQUE (suggestion_id, rank),
    CONSTRAINT uk_suggested_recipe_suggestion_recipe UNIQUE (suggestion_id, recipe_id)
);

CREATE TABLE meal_plan (
    meal_plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    plan_date DATE NOT NULL,
    title VARCHAR(255) NOT NULL,
    CONSTRAINT fk_meal_plan_suggestion
        FOREIGN KEY (suggestion_id) REFERENCES ai_suggestion (suggestion_id) ON DELETE CASCADE
);

CREATE TABLE meal_plan_item (
    meal_plan_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_plan_id BIGINT NOT NULL,
    recipe_id BIGINT NOT NULL,
    meal_type meal_type_enum NOT NULL,
    scheduled_time TIME NOT NULL,
    CONSTRAINT fk_meal_plan_item_plan
        FOREIGN KEY (meal_plan_id) REFERENCES meal_plan (meal_plan_id) ON DELETE CASCADE
);

CREATE INDEX idx_ai_suggestion_user ON ai_suggestion (user_id);
CREATE INDEX idx_ai_suggestion_generated_at ON ai_suggestion (generated_at);
CREATE INDEX idx_suggested_recipe_suggestion ON suggested_recipe (suggestion_id);
CREATE INDEX idx_suggested_recipe_recipe ON suggested_recipe (recipe_id);
CREATE INDEX idx_meal_plan_user_date ON meal_plan (user_id, plan_date);
CREATE INDEX idx_meal_plan_suggestion ON meal_plan (suggestion_id);
CREATE INDEX idx_meal_plan_item_plan ON meal_plan_item (meal_plan_id);
CREATE INDEX idx_meal_plan_item_recipe ON meal_plan_item (recipe_id);
