CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(1000),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE allergens (
    allergen_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_allergens_name UNIQUE (name)
);

CREATE TABLE ingredients (
    ingredient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    CONSTRAINT uk_ingredients_name UNIQUE (name)
);

CREATE TABLE ingredient_allergens (
    ingredient_id BIGINT NOT NULL,
    allergen_id BIGINT NOT NULL,
    PRIMARY KEY (ingredient_id, allergen_id),
    CONSTRAINT fk_ingredient_allergens_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id),
    CONSTRAINT fk_ingredient_allergens_allergen FOREIGN KEY (allergen_id) REFERENCES allergens (allergen_id)
);

CREATE TABLE recipes (
    recipe_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    image_url VARCHAR(2048),
    preparation_time INTEGER NOT NULL,
    cook_time INTEGER NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    servings INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_recipes_category FOREIGN KEY (category_id) REFERENCES categories (category_id),
    CONSTRAINT ck_recipes_preparation_time CHECK (preparation_time >= 0),
    CONSTRAINT ck_recipes_cook_time CHECK (cook_time >= 0),
    CONSTRAINT ck_recipes_servings CHECK (servings > 0)
);

CREATE TABLE recipe_diet_types (
    recipe_id BIGINT NOT NULL,
    diet_type VARCHAR(30) NOT NULL,
    PRIMARY KEY (recipe_id, diet_type),
    CONSTRAINT fk_recipe_diet_types_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE
);

CREATE TABLE recipe_ingredients (
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    quantity DECIMAL(12, 3) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    PRIMARY KEY (recipe_id, ingredient_id),
    CONSTRAINT fk_recipe_ingredients_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredients_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients (ingredient_id),
    CONSTRAINT ck_recipe_ingredients_quantity CHECK (quantity > 0)
);

CREATE TABLE recipe_steps (
    step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    step_order INTEGER NOT NULL,
    instruction TEXT NOT NULL,
    CONSTRAINT uk_recipe_steps_order UNIQUE (recipe_id, step_order),
    CONSTRAINT fk_recipe_steps_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT ck_recipe_steps_order CHECK (step_order > 0)
);

CREATE TABLE nutrition_info (
    nutrition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    calories DECIMAL(10, 2) NOT NULL,
    protein DECIMAL(10, 2) NOT NULL,
    fat DECIMAL(10, 2) NOT NULL,
    carbs DECIMAL(10, 2) NOT NULL,
    fiber DECIMAL(10, 2) NOT NULL,
    sugar DECIMAL(10, 2) NOT NULL,
    sodium DECIMAL(10, 2) NOT NULL,
    CONSTRAINT uk_nutrition_info_recipe UNIQUE (recipe_id),
    CONSTRAINT fk_nutrition_info_recipe FOREIGN KEY (recipe_id) REFERENCES recipes (recipe_id) ON DELETE CASCADE,
    CONSTRAINT ck_nutrition_nonnegative CHECK (
        calories >= 0 AND protein >= 0 AND fat >= 0 AND carbs >= 0
        AND fiber >= 0 AND sugar >= 0 AND sodium >= 0
    )
);

CREATE INDEX idx_recipes_title ON recipes (title);
CREATE INDEX idx_recipes_category ON recipes (category_id);
CREATE INDEX idx_ingredients_name ON ingredients (name);
CREATE INDEX idx_recipe_ingredients_ingredient ON recipe_ingredients (ingredient_id);
